AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role StackSet for AWS Config Custom Rule Lambda

Resources:
  ConfigLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ConfigLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ConfigLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - config:PutEvaluations
                Resource: '*'
              - Effect: Allow
                Action:
                  - tag:GetResources
                  - tag:GetTagValues
                  - tag:GetTagKeys
                  - tag:TagResources
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

Outputs:
  ConfigLambdaRoleARN:
    Description: ARN of the IAM Role for the AWS Config Custom Rule Lambda
    Value: !GetAtt ConfigLambdaRole.Arn